####
# Installs Java openJDK 8 in the usgs/centos image by extending the
# openjdk:base image.
#
# Image: usgsnshmp/nshmp-openjdk:jdk8
####

# Java openJDK version to install
ARG JAVA_VERSION=1.8.0

# Install JDK
ARG INSTALL_JDK=true

####
# From Image: usgsnshmp/nshmp-java:base
# Description: Install Java openJDK 8 from nshmp-openjdk base image.
####
FROM usgsnshmp/openjdk:base
