####
# Installs Java JRE 8 in the usgs/centos image by extending the
# openjdk:base image.
#
# Image: usgsnshmp/nshmp-openjdk:jre8
####

# Java JRE version to install
ARG JAVA_VERSION=1.8.0

# Install JRE
ARG INSTALL_JDK=false

####
# From Image: usgsnshmp/nshmp-java:base
# Description: Install Java JRE 8 from nshmp-openjdk base image.
####
FROM usgsnshmp/openjdk:base
