####
# Installs Java openJDK 11 in the usgs/centos image by extending the
# openjdk:base image.
#
# Image: usgsnshmp/nshmp-openjdk:jdk11
####

# Java openJDK version to install
ARG JAVA_VERSION=11

# Install JDK
ARG INSTALL_JDK=true

####
# From Image: usgsnshmp/nshmp-java:base
# Description: Install Java openJDK 11 from nshmp-openjdk base image.
####
FROM usgsnshmp/openjdk:base
